services:
  backend:
    build:
      context: ./Portifolio_Back_end
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./Portifolio_Back_end:/app

  frontend:
    build:
      context: ./Portifolio_Front_end
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Portifolio_Front_end:/app
    depends_on:
      - backend  # O frontend sรณ sobe depois do backend
