# Usar imagem do Node.js
FROM node:18-alpine

# Definir diretório de trabalho
WORKDIR /app

# Copiar arquivos para dentro do contêiner
COPY . .

# Instalar dependências
RUN npm install

# Adicionar permissão de execução para os binários do node_modules
RUN chmod +x /app/node_modules/.bin/*

# Expor porta do React
EXPOSE 3000

# Iniciar o servidor do React
CMD ["npm", "start"]
