# Usar a imagem do Node.js
FROM node:18-alpine

# Definir diretório de trabalho
WORKDIR /app

# Copiar arquivos do projeto
COPY . .

# Instalar dependências
RUN npm install

# Construir o projeto
RUN npm run build

# Expor porta do Vite
EXPOSE 5173

# Comando para iniciar o frontend
CMD ["npm", "run", "dev", "--", "--host"]