# Usar a imagem oficial do Python
FROM python:3.11

# Definir diretório de trabalho
WORKDIR /app

# Copiar arquivos do projeto
COPY . .

# Criar e ativar ambiente virtual
RUN python -m venv venv
RUN /bin/bash -c "source venv/bin/activate && pip install --no-cache-dir -r requirements.txt"

# Expor porta do Django
EXPOSE 8000

# Comando para iniciar o backend com ambiente virtual ativado
CMD ["/bin/bash", "-c", "source venv/bin/activate && python manage.py runserver 0.0.0.0:8000"]
