# Usar a imagem oficial do Python
FROM python:3.11

# Definir diretório de trabalho
WORKDIR /app

# Copiar os arquivos do projeto para o container
COPY . .

# Instalar dependências do Django
RUN pip install --no-cache-dir -r requirements.txt

# Expor a porta do Django
EXPOSE 8000

# Comando para iniciar o backend
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
