services:
  - type: web
    name: meu-portifolio-backend
    env: python
    plan: free
    rootDir: Portifolio_Back_end  # Mantendo a pasta correta do backend
    buildCommand:  |
        chmod +x wait_for_db.sh
        pip install --no-cache-dir -r requirements.txt
    startCommand: bash -c "./wait_for_db.sh && python manage.py migrate && gunicorn Portifolio_Back_end.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meu-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"

databases:
  - name: meu-db
    plan: free
    databaseName: meuportifolio
    user: meuportifolio_user
